version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:80"
    env_file: 
      - .env
    depends_on:
      - local_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    restart: unless-stopped

  local_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: 
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h local_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local